### PR TITLE
Pluralise the 'searchrawtransaction' command.

### PR DESCRIPTION
**Pull request by Roasbeef**
Related to btcsuite/btcd#205. Changed to match the `bitcoind` fork supporting a similar RPC call.

### CODE REVIEW

**Comment by davecgh** [comment]
OK

**Comment by davecgh** [comment]
On second look, the verbose parameter is a bool here while it is in an int in the BC API.  I much prefer a bool, but for compatibility these have to match.  The same thing is true for `getrawtransaction`: https://github.com/btcsuite/btcjson/blob/578d1debc5a33c908a547a5460131663ef4b0c42/jsoncmd.go#L3196

**Comment by Roasbeef** [comment]
Changed to take an int for the `verbose` parameter instead of a bool. Wish all the commands were consistent across the board...(some take `bool` for verbose, some `int`)

**Comment by davecgh** [comment]
Thanks.  I agree about the inconsistencies.  As I said in the other thread, it drives me insane, but if we want to be compatible we're stuck with it.

**Comment by davecgh** [comment]
Would you squash this to a single commit?  It's good to go after that.

**Comment by Roasbeef** [comment]
Done, squashed and updated the commit message.

**Pull request merged**
